[package]
name = "ic"
version = "3.0.0"
description = "IC management canister interface (aaaaa-aa)"
repository = "https://github.com/ZenVoich/ic"
keywords = [ "ic", "types", "interface", "http" ]
license = "MIT"

[dependencies]
base = "0.14.14"

[requirements]
moc = "0.14.10"

[toolchain]
moc = "0.14.14"

[dev-dependencies]
test = "2.1.1"
