[package]
name = "ic"
version = "2.0.0"
description = "IC management canister interface (aaaaa-aa)"
repository = "https://github.com/ZenVoich/ic"
keywords = [ "ic", "types", "interface" ]
license = "MIT"

[toolchain]
moc = "0.14.10"